### ISSUE TITLE
which version of the three party libraries are used?

### ISSUE THREAD

**Issue by CrazyPeter** [zhangguof/mkrkr#1]
Hello, can you elaborate on which version of the three party libraries are used?

**Comment by zhangguof** [comment]
build success with macos 10.14.6, xcode 11.3.
third-part libs:
freetype 2.9
SDL2 2.0.8
boost 1.69
ffmpeg 4.0

**Comment by CrazyPeter** [comment]
Thanks♪(･ω･)ﾉ
If there is a donation channel?
I hope to donate a cup of coffee☕️.

**Comment by zhangguof** [comment]
Thank you for your interest in this project.
I'm glad to hear someone like it.
